- name: checking the condition
  hosts: local
  connection: local
  vars:
    human_heart_beat: 72

  tasks:
  - name: check the human heart beat
    when: human_heart_beat < 70
    debug:
      msg: "The human heart beat should be more than 70, i.e. {{ human_heart_beat }}"

#This condition is false so we will not get any output for this playbook.      