- name: check the condition
  hosts: local
  connection: local
  vars:
    movie_ticket_price: 150
  tasks:
  - name: check the movie ticket price
    when: movie_ticket_price > 100
    debug:
      msg: "Yes, the movies ticket price is more than 100, i.e. {{ movie_ticket_price }}"