- name: installing the package using the condition
  hosts: frontend
  become: yes
  tasks:
  - name: print if redhat
    debug:
      msg: "OS family is redhat, package manager is dnf"
    when: ansible_facts.os_family == "Redhat"  

  - name: print if Debian
    debug:
      msg: "OS family is Debian, package manager is apt"
    when: ansible_facts.os_family == "Debian"  