- name: peddi mvoie info
  hosts: local
  connection: local
  vars:
    name: peddi #string
    duration_in_mins: 120 #integer/number
    is_release: yes #boolean
    languages: ["english", "hindi", "kannada"]
    movie_contains: #list
      - action
      - songs & dance
      - comedy
      - emotion drama
    more_info:  #map/dictionary
      hero: "Ram Charan"
      heroine: "Janvi kapoor"
      director: "Buchi babu"

  tasks:
  - name: printing the peddi movie info
    debug:
      msg: "The movie name is {{ name }}, the duration is {{ duration_in_mins }} mins, is it realeased: {{ is_release}}, what peddi movie contains: {{ movie_contains }}, more info: {{ more_info}}"

