- name: demo on command vs shell
  hosts: local
  connection: local
  tasks:
  - name: command test
    command: touch file1.txt
    register: command_output_1

  - name: command test with shell env
    command: touch > /temp/file2.txt
    register: command_output_2

  - name: print bothe the outputs
    debug:  
      msg:
        - "command1 output is {{ command_output_1 }}"
        - "command2 output is {{ command_output_2 }}"