- name: demo on command vs shell
  hosts: local
  connection: local
  tasks:
  - name: command test
    command: touch file1.txt
    register: command_output_1

  - name: shell test
    # command: touch > /temp/file2.txt #here special variable '>' is used so command will not, need to shell
    shell: touch /tmp/file2.txt 
    register: command_output_2

  - name: shell test2
    #command: cat /etc/passwd | grep root
    shell: cat /etc/passwd | grep root
    register: users_output

  - name: print both the outputs
    debug:  
      msg:
        - "command1 output is {{ command_output_1 }}"
        - "command2 output is {{ command_output_2 }}"
        - "users output is {{ users_output }}"