- name: demo on error handling
  hosts: local
  connection: local
  become: true

  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_output
    ignore_errors: yes

  - name: Create user roboshop
    command: useradd roboshop
    when: user_output.rc != 0
    
  - name: print the user info
    debug:
      msg: "user status {{user_output}}"

