- name: demo on error handling
  hosts: local
  connection: local
  become: true

  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_output
    igonre_errors: yes

    debug:
      msg: "user status {{user_output}}"

  - name: Create user roboshop
    command: useradd roboshop
  when: user_output.rc != 0
