- name: Convert dictonary to items
  hosts: local
  connection: local
  vars:
    tagmap: 
      name: Ansible
      course: DevOps
      sector: I.T

  tasks:
  - name: Converting the map to list
    debug: 
      msg: "{{ tagmap | dict2items }}"

#list==items
#map==dict