- name: Convert dictonary to items
  hosts: local
  connection: local
  vars:
    tagmap: 
      name: Ansible
      course: DevOps
      sector: I.T

  tasks:
  - name: Converting the map to list
    debug: 
      msg: " {{ tagmap | dict2items | to_nice_yaml }} "

# dict2items It'll change dictionary to list