- name: Declaring the variable from the cmd line
  hosts: local
  connection: local
  tasks:
  - name: Defining variable in cmd line
    debug: 
      msg: " {{ NAME | default ('hi' ' ' 'Muddukrishna') }} " 

#NAME Variable is not declared under vars, directly giving   
#default is filter to help to pass the variables here  