- name: About filters concept
  hosts: local
  connection: local
  vars:
    topics: ansible, shell, terraform, python
  tasks:
  - name: making list
    debug:
      msg: "{{ topics | (',') }}"
      

