- name: create user
  become: yes
  hosts: local
  connection: local
  tasks:
  - name: create expense user
    user:
      name: krish # useradd expense
  - name: printing the user info
    debug:
      msg: "{{ name }}"