---
- name: printing username name and password using read
  hosts: localhost
  connection: local
  vars_prompt:   #vars_prompt is used to prompt the user for input during playbook execution. It allows you to gather information from the user, such as usernames, passwords, or any other data that you want to use in your playbook.
  - name: "username"
    prompt: "Enter your username"
    private: false

  - name: "password"
    prompt: "Enter your password"
    private: true
  tasks:
  - name: printing the username and password
    debug:
      msg: "The username is {{ username }} and the password is ********"
