---
- name: printing username name and password using read
  hosts: localhost
  connection: local
  vars_prompt:   #vars_prompt is used to prompt the user for input during playbook execution. It allows you to gather information from the user, such as usernames, passwords, or any other data that you want to use in your playbook.
  - name: "username"
    prompt: "Enter your username"
    private: false

  - name: "password"
    prompt: "Enter your password"
    private: true
  tasks:
  - name: printing the username and password
    debug:
      msg: "The username is {{ username }} and the password is {{ password }}"
      #msg: "The username is {{ username }} and the password is ********" #This is a common practice to avoid displaying sensitive information like passwords in logs or output. By replacing the actual password with asterisks (********), you can prevent unauthorized access to the password while still indicating that it has been entered.
      
