---
- name: printing variables
  hosts: localhost
  connection: local
  vars:
  - course.yaml
  tasks:
  - name: printing the var info
    debug:
      msg: " {{ learner }} is learning {{ course }} under guidance of {{ trainer }}."
      
    