- name: Demo on group_vars
  hosts: frontend
  #connection: local
  tasks:
  - name: printing the information
    debug:
      msg: "The course name is {{ COURSE }}, the trainer name is {{ TRAINER }} and the batch name is {{ BATCH }}"