---
- name: Printing info using play level vars and task level vars
  hosts: localhost
  connection: local
  vars:
    learner: Muddukrishna
    course: DevOps
    trainer: siva kumar

  tasks:
  - name: printing the var info
    vars:
      course: DevOps+AIOps
    ansible.builtin.debug:
      msg: |
        {{ learner }} is learninng {{ course }} under guidance of {{ trainer }}
        See Task level variable overwrites the play level variable.
        Task level won.


     